### ISSUE TITLE
Open call for people's linker profilings

### ISSUE THREAD

**Issue by michaeleisel** [michaeleisel/zld#17]
The linker has many ways of using it, and many potential bottlenecks. By sending me a profiling (using the time profiler) of `zld`, and ideally one of stock `ld` as well, I can improve the linker for your exact use case!

In addition, if it's possible for your case, it'd be nice to see the invocation (helpful) and/or get the full set of input files to reproduce on my end (extremely helpful)

**Comment by milend** [comment]
@michaeleisel: One thing that would be useful is being able to instruct `zld` to not begin linking until it receives a specific signal (e.g., `SIGUSR1`). The use case is to start `zld` in a paused mode, attach Time Profiler to it and then send `SIGUSR1` to start linking. This way, we do not have to record full system profiles (due to privacy concerns).

**Comment by michaeleisel** [comment]
@milend thinking about it more, a system profiling isn't necessary. zld can be profiled on its own, and using the scheme settings for profiling, it can use the exact same working directory and flags as it would during normal running

**Comment by milend** [comment]
@michaeleisel Makes sense! The reason why the signal approach might be easier is when have external build system call zld/ld64 directly and running it manually is a bit inconvenient (not impossible, just more work depending on build system). Either way, it's a low-pro issue that would just make it easier to collect profiles.

**Comment by milend** [comment]
Attached samples in #38.

**Comment by michaeleisel** [comment]
Closing for now
