### ISSUE TITLE
Pre-parsing breaks linking

### ISSUE THREAD

**Issue by rmaz** [michaeleisel/zld#21]
The changes landed in #19 cause the linker to fail for our codebase. 

[zld_2020-03-05-130236_richardh-C02XG1KJJGH6.crash.txt](https://github.com/michaeleisel/zld/files/4295155/zld_2020-03-05-130236_richardh-C02XG1KJJGH6.crash.txt)
[zld_2020-03-05-130342_richardh-C02XG1KJJGH6.crash.txt](https://github.com/michaeleisel/zld/files/4295156/zld_2020-03-05-130342_richardh-C02XG1KJJGH6.crash.txt)

<img width="1076" alt="Screen Shot 2020-03-05 at 1 12 30 PM" src="https://user-images.githubusercontent.com/728850/76026107-00122e00-5ee3-11ea-958b-c85e96061137.png">

**Comment by michaeleisel** [comment]
Interesting, they passed all unit tests. I'll take a look

**Comment by michaeleisel** [comment]
Is this error deterministic?

**Comment by michaeleisel** [comment]
Also, if you have a sec it'd be great to know what happens when you run it with address sanitizer (thread sanitizer is currently difficult because of tbb false positives)

**Comment by rmaz** [comment]
It does not always occur in exactly the same place, but it crashes consistently, yes. I'll try and find time to run it through the sanitizer this afternoon.

**Comment by michaeleisel** [comment]
#24 should fix your issues. I'll do a full test of it when I revamp unit testing next week

**Comment by michaeleisel** [comment]
Heap allocation might work, but I see `pthread_attr_setstacksize(&attr, 8 * 1024 * 1024);` in `InputFiles::startThread`. So even on background threads, it's been used to a certain size. I think to reduce future issues, and since NSOperationQueue doesn't seem to allow stack size customization, I'll interpose `pthread_create` and set the stack size there
