### ISSUE TITLE
Potential optimizations

### ISSUE THREAD

**Issue by kastiglione** [michaeleisel/zld#6]
The `-no_uuid` suggestion led me to relook at an Instruments trace of our project. In addition to `-no_uuid` (which was ~3.5% in the project I looked at), I found some other flags that may be useful optimizations. I was wondering if you've tried any of these:

**`-no_deduplicate`**

The `dedup` pass is the most expensive pass in our project, around 8%. For functions, this seems fine, but does this result in duplicate data symbols? That would be a problem for mutable data. I presume some of the time saved here is paid back at runtime (larger binary).

**`-no_compact_unwind`**

The `compact_unwind` is the next slowest pass in my profile, 3.2%. Our project is all Swift, no C++ and so I don't think we care about compact unwind info (for developer builds at least).

Other flags I added, that don't seem to have saved a lot of time in our project: `-no_order_inits`, `-no_order_data`, `-no_function_starts`.

**Comment by michaeleisel** [comment]
`-no_deduplicate` is a good one. For Xcode, the default is to add `-no_deduplicate` for Debug but to deduplicate for Release. 

`-no_compact_unwind` seems a little more interesting. I'm not sure it's really language-specific, I believe it's helping at the assembly level to backtrace, a la https://www.mikeash.com/pyblog/friday-qa-2012-04-27-plcrashreporter-and-unwinding-the-stack-with-dwarf.html . I'd like to understand the exact situations in which it can be a drawback to use flag (although it definitely seems good for debug in general)

**Comment by bjorn3** [comment]
> I'd like to understand the exact situations in which it can be a drawback to use flag

It increases the size of the binary.

**Comment by michaeleisel** [comment]
Yes, binary size increase is a downside. But the CPU cost of a larger binary size (e.g., due to more page faults) may generally compensated for by the linker being faster. I think we can let consumers test that for themselves.

Besides size, it seems like Objective-C and C++ exceptions use compact unwind info, but Swift does not. Also, if an Objective-C method throws and unwinds into a Swift context, Swift still doesn't need compact unwind info. So for a pure Swift project like @kastiglione is working with, it indeed seems fine. Then there's that article, which discusses `backtrace` being unsuitable for crash reporting, and so needing compact unwind info. But since this is a debug build, that's not as much of a concern anyways

**Comment by michaeleisel** [comment]
Closing, will resume discussion in https://github.com/michaeleisel/zld/pull/7
